### PR TITLE
Fix compilation on the latest nightly

### LINKED ISSUE #16: Unable to compile with latest nightly
I have the following error (I removed duplicated errors to reduce log):

```
error[E0557]: feature has been removed
 --> /home/gena/.cargo/registry/src/github.com-1ecc6299db9ec823/crystalorb-0.2.1/src/lib.rs:4:12
  |
4 | #![feature(const_generics)]
  |            ^^^^^^^^^^^^^^ feature has been removed
  |
  = note: removed in favor of `#![feature(adt_const_params)]` and `#![feature(generic_const_exprs)]`

   Compiling time v0.2.27
error: `TerminationCondition` is forbidden as the type of a const generic parameter
  --> /home/gena/.cargo/registry/src/github.com-1ecc6299db9ec823/crystalorb-0.2.1/src/fixed_timestepper.rs:92:56
   |
92 | impl<T: FixedTimestepper, const TERMINATION_CONDITION: TerminationCondition>
   |                                                        ^^^^^^^^^^^^^^^^^^^^
   |
   = note: the only supported types are integers, `bool` and `char`
   = help: more complex types are supported with `#![feature(adt_const_params)]`

For more information about this error, try `rustc --explain E0557`.
error: could not compile `crystalorb` due to 10 previous errors
warning: build failed, waiting for other jobs to finish...
error: build failed
```

I use `rustc 1.57.0-nightly (11491938f 2021-09-29)`

### PR DESCRIPTION
**Pull request by Shatur**
The feature `const_generics` was spitted to `adt_const_params` and `generic_const_exprs`, see more infor [here](https://blog.rust-lang.org/inside-rust/2021/09/06/Splitting-const-generics.html). So in this PR I replaced `const_generics` with `adt_const_params`. But the compiler complains that the feature is incomplete, so I added `incomplete_features` to `allow`.

Also I removed `extended_key_value_attributes` since it was stabilized in 1.54.0.

Fixes #16.

### CODE REVIEW

**Review by ErnWong — DISMISSED** [review]
Thanks!

**Comment by Shatur** [comment]
Fixed other warnings that caused issues with CI.

**Review by ErnWong — APPROVED** [review]

**Comment by ErnWong** [comment]
Cheers!

**Comment by Shatur** [comment]
@ErnWong looks like something wrong with your token for test coverage?

**Comment by ErnWong** [comment]
Yeah. If I remember correctly, GitHub Actions doesn't share my test coverage token secret to the `test-coverage` PR check for forks (I might be wrong - I'll need to double check someday). I also remember reading somewhere that a token isn't actually required for public repos, but last time I tried it, I seemed to had difficulty getting it working without a token.

**Pull request merged**
